--------------------------------------------------------
--  DDL for Table CHANNELS
--------------------------------------------------------

  CREATE TABLE "SH"."CHANNELS" 
   (	"CHANNEL_ID" NUMBER, 
	"CHANNEL_DESC" VARCHAR2(20 BYTE), 
	"CHANNEL_CLASS" VARCHAR2(20 BYTE), 
	"CHANNEL_CLASS_ID" NUMBER, 
	"CHANNEL_TOTAL" VARCHAR2(13 BYTE), 
	"CHANNEL_TOTAL_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SH"."CHANNELS"."CHANNEL_ID" IS 'primary key column';
   COMMENT ON COLUMN "SH"."CHANNELS"."CHANNEL_DESC" IS 'e.g. telesales, internet, catalog';
   COMMENT ON COLUMN "SH"."CHANNELS"."CHANNEL_CLASS" IS 'e.g. direct, indirect';
   COMMENT ON TABLE "SH"."CHANNELS"  IS 'small dimension table';
--------------------------------------------------------
--  DDL for Index CHANNELS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SH"."CHANNELS_PK" ON "SH"."CHANNELS" ("CHANNEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CHANNELS
--------------------------------------------------------

  ALTER TABLE "SH"."CHANNELS" MODIFY ("CHANNEL_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."CHANNELS" MODIFY ("CHANNEL_DESC" NOT NULL ENABLE);
  ALTER TABLE "SH"."CHANNELS" MODIFY ("CHANNEL_CLASS" NOT NULL ENABLE);
  ALTER TABLE "SH"."CHANNELS" MODIFY ("CHANNEL_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."CHANNELS" MODIFY ("CHANNEL_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SH"."CHANNELS" MODIFY ("CHANNEL_TOTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."CHANNELS" ADD CONSTRAINT "CHANNELS_PK" PRIMARY KEY ("CHANNEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE NOVALIDATE;


--------------------------------------------------------
--  DDL for Table COUNTRIES
--------------------------------------------------------

  CREATE TABLE "SH"."COUNTRIES" 
   (	"COUNTRY_ID" NUMBER, 
	"COUNTRY_ISO_CODE" CHAR(2 BYTE), 
	"COUNTRY_NAME" VARCHAR2(40 BYTE), 
	"COUNTRY_SUBREGION" VARCHAR2(30 BYTE), 
	"COUNTRY_SUBREGION_ID" NUMBER, 
	"COUNTRY_REGION" VARCHAR2(20 BYTE), 
	"COUNTRY_REGION_ID" NUMBER, 
	"COUNTRY_TOTAL" VARCHAR2(11 BYTE), 
	"COUNTRY_TOTAL_ID" NUMBER, 
	"COUNTRY_NAME_HIST" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SH"."COUNTRIES"."COUNTRY_ID" IS 'primary key';
   COMMENT ON COLUMN "SH"."COUNTRIES"."COUNTRY_NAME" IS 'country name';
   COMMENT ON COLUMN "SH"."COUNTRIES"."COUNTRY_SUBREGION" IS 'e.g. Western Europe, to allow hierarchies';
   COMMENT ON COLUMN "SH"."COUNTRIES"."COUNTRY_REGION" IS 'e.g. Europe, Asia';
   COMMENT ON TABLE "SH"."COUNTRIES"  IS 'country dimension table (snowflake)';
--------------------------------------------------------
--  DDL for Index COUNTRIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SH"."COUNTRIES_PK" ON "SH"."COUNTRIES" ("COUNTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COUNTRIES
--------------------------------------------------------

  ALTER TABLE "SH"."COUNTRIES" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."COUNTRIES" MODIFY ("COUNTRY_ISO_CODE" NOT NULL ENABLE);
  ALTER TABLE "SH"."COUNTRIES" MODIFY ("COUNTRY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SH"."COUNTRIES" MODIFY ("COUNTRY_SUBREGION" NOT NULL ENABLE);
  ALTER TABLE "SH"."COUNTRIES" MODIFY ("COUNTRY_SUBREGION_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."COUNTRIES" MODIFY ("COUNTRY_REGION" NOT NULL ENABLE);
  ALTER TABLE "SH"."COUNTRIES" MODIFY ("COUNTRY_REGION_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."COUNTRIES" MODIFY ("COUNTRY_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SH"."COUNTRIES" MODIFY ("COUNTRY_TOTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."COUNTRIES" ADD CONSTRAINT "COUNTRIES_PK" PRIMARY KEY ("COUNTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE NOVALIDATE;


--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "SH"."CUSTOMERS" 
   (	"CUST_ID" NUMBER, 
	"CUST_FIRST_NAME" VARCHAR2(20 BYTE), 
	"CUST_LAST_NAME" VARCHAR2(40 BYTE), 
	"CUST_GENDER" CHAR(1 BYTE), 
	"CUST_YEAR_OF_BIRTH" NUMBER(4,0), 
	"CUST_MARITAL_STATUS" VARCHAR2(20 BYTE), 
	"CUST_STREET_ADDRESS" VARCHAR2(40 BYTE), 
	"CUST_POSTAL_CODE" VARCHAR2(10 BYTE), 
	"CUST_CITY" VARCHAR2(30 BYTE), 
	"CUST_CITY_ID" NUMBER, 
	"CUST_STATE_PROVINCE" VARCHAR2(40 BYTE), 
	"CUST_STATE_PROVINCE_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"CUST_MAIN_PHONE_NUMBER" VARCHAR2(25 BYTE), 
	"CUST_INCOME_LEVEL" VARCHAR2(30 BYTE), 
	"CUST_CREDIT_LIMIT" NUMBER, 
	"CUST_EMAIL" VARCHAR2(50 BYTE), 
	"CUST_TOTAL" VARCHAR2(14 BYTE), 
	"CUST_TOTAL_ID" NUMBER, 
	"CUST_SRC_ID" NUMBER, 
	"CUST_EFF_FROM" DATE, 
	"CUST_EFF_TO" DATE, 
	"CUST_VALID" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_ID" IS 'primary key';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_FIRST_NAME" IS 'first name of the customer';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_LAST_NAME" IS 'last name of the customer';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_GENDER" IS 'gender; low cardinality attribute';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_YEAR_OF_BIRTH" IS 'customer year of birth';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_MARITAL_STATUS" IS 'customer marital status; low cardinality attribute';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_STREET_ADDRESS" IS 'customer street address';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_POSTAL_CODE" IS 'postal code of the customer';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_CITY" IS 'city where the customer lives';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_STATE_PROVINCE" IS 'customer geography: state or province';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."COUNTRY_ID" IS 'foreign key to the countries table (snowflake)';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_MAIN_PHONE_NUMBER" IS 'customer main phone number';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_INCOME_LEVEL" IS 'customer income level';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_CREDIT_LIMIT" IS 'customer credit limit';
   COMMENT ON COLUMN "SH"."CUSTOMERS"."CUST_EMAIL" IS 'customer email id';
   COMMENT ON TABLE "SH"."CUSTOMERS"  IS 'dimension table';
--------------------------------------------------------
--  DDL for Index CUSTOMERS_GENDER_BIX
--------------------------------------------------------

  CREATE BITMAP INDEX "SH"."CUSTOMERS_GENDER_BIX" ON "SH"."CUSTOMERS" ("CUST_GENDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_MARITAL_BIX
--------------------------------------------------------

  CREATE BITMAP INDEX "SH"."CUSTOMERS_MARITAL_BIX" ON "SH"."CUSTOMERS" ("CUST_MARITAL_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_YOB_BIX
--------------------------------------------------------

  CREATE BITMAP INDEX "SH"."CUSTOMERS_YOB_BIX" ON "SH"."CUSTOMERS" ("CUST_YEAR_OF_BIRTH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SH"."CUSTOMERS_PK" ON "SH"."CUSTOMERS" ("CUST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_GENDER" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_YEAR_OF_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_STREET_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_POSTAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_CITY" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_CITY_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_STATE_PROVINCE" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_STATE_PROVINCE_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_MAIN_PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" MODIFY ("CUST_TOTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE NOVALIDATE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "SH"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_COUNTRY_FK" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "SH"."COUNTRIES" ("COUNTRY_ID") ENABLE NOVALIDATE;


--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "SH"."PRODUCTS" 
   (	"PROD_ID" NUMBER(6,0), 
	"PROD_NAME" VARCHAR2(50 BYTE), 
	"PROD_DESC" VARCHAR2(4000 BYTE), 
	"PROD_SUBCATEGORY" VARCHAR2(50 BYTE), 
	"PROD_SUBCATEGORY_ID" NUMBER, 
	"PROD_SUBCATEGORY_DESC" VARCHAR2(2000 BYTE), 
	"PROD_CATEGORY" VARCHAR2(50 BYTE), 
	"PROD_CATEGORY_ID" NUMBER, 
	"PROD_CATEGORY_DESC" VARCHAR2(2000 BYTE), 
	"PROD_WEIGHT_CLASS" NUMBER(3,0), 
	"PROD_UNIT_OF_MEASURE" VARCHAR2(20 BYTE), 
	"PROD_PACK_SIZE" VARCHAR2(30 BYTE), 
	"SUPPLIER_ID" NUMBER(6,0), 
	"PROD_STATUS" VARCHAR2(20 BYTE), 
	"PROD_LIST_PRICE" NUMBER(8,2), 
	"PROD_MIN_PRICE" NUMBER(8,2), 
	"PROD_TOTAL" VARCHAR2(13 BYTE), 
	"PROD_TOTAL_ID" NUMBER, 
	"PROD_SRC_ID" NUMBER, 
	"PROD_EFF_FROM" DATE, 
	"PROD_EFF_TO" DATE, 
	"PROD_VALID" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_ID" IS 'primary key';
   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_NAME" IS 'product name';
   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_DESC" IS 'product description';
   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_SUBCATEGORY" IS 'product subcategory';
   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_SUBCATEGORY_DESC" IS 'product subcategory description';
   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_CATEGORY" IS 'product category';
   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_CATEGORY_DESC" IS 'product category description';
   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_WEIGHT_CLASS" IS 'product weight class';
   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_UNIT_OF_MEASURE" IS 'product unit of measure';
   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_PACK_SIZE" IS 'product package size';
   COMMENT ON COLUMN "SH"."PRODUCTS"."SUPPLIER_ID" IS 'this column';
   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_STATUS" IS 'product status';
   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_LIST_PRICE" IS 'product list price';
   COMMENT ON COLUMN "SH"."PRODUCTS"."PROD_MIN_PRICE" IS 'product minimum price';
   COMMENT ON TABLE "SH"."PRODUCTS"  IS 'dimension table';
--------------------------------------------------------
--  DDL for Index PRODUCTS_PROD_STATUS_BIX
--------------------------------------------------------

  CREATE BITMAP INDEX "SH"."PRODUCTS_PROD_STATUS_BIX" ON "SH"."PRODUCTS" ("PROD_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PROD_SUBCAT_IX
--------------------------------------------------------

  CREATE INDEX "SH"."PRODUCTS_PROD_SUBCAT_IX" ON "SH"."PRODUCTS" ("PROD_SUBCATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PROD_CAT_IX
--------------------------------------------------------

  CREATE INDEX "SH"."PRODUCTS_PROD_CAT_IX" ON "SH"."PRODUCTS" ("PROD_CATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SH"."PRODUCTS_PK" ON "SH"."PRODUCTS" ("PROD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_NAME" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_DESC" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_SUBCATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_SUBCATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_SUBCATEGORY_DESC" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_CATEGORY_DESC" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_WEIGHT_CLASS" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_PACK_SIZE" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_LIST_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_MIN_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" MODIFY ("PROD_TOTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PROD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE NOVALIDATE;


--------------------------------------------------------
--  DDL for Table PROMOTIONS
--------------------------------------------------------

  CREATE TABLE "SH"."PROMOTIONS" 
   (	"PROMO_ID" NUMBER(6,0), 
	"PROMO_NAME" VARCHAR2(30 BYTE), 
	"PROMO_SUBCATEGORY" VARCHAR2(30 BYTE), 
	"PROMO_SUBCATEGORY_ID" NUMBER, 
	"PROMO_CATEGORY" VARCHAR2(30 BYTE), 
	"PROMO_CATEGORY_ID" NUMBER, 
	"PROMO_COST" NUMBER(10,2), 
	"PROMO_BEGIN_DATE" DATE, 
	"PROMO_END_DATE" DATE, 
	"PROMO_TOTAL" VARCHAR2(15 BYTE), 
	"PROMO_TOTAL_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_ID" IS 'primary key column';
   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_NAME" IS 'promotion description';
   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_SUBCATEGORY" IS 'enables to investigate promotion hierarchies';
   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_CATEGORY" IS 'promotion category';
   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_COST" IS 'promotion cost, to do promotion effect calculations';
   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_BEGIN_DATE" IS 'promotion begin day';
   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_END_DATE" IS 'promotion end day';
   COMMENT ON TABLE "SH"."PROMOTIONS"  IS 'dimension table without a PK-FK relationship with the facts table, to show outer join functionality';
--------------------------------------------------------
--  DDL for Index PROMO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SH"."PROMO_PK" ON "SH"."PROMOTIONS" ("PROMO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROMOTIONS
--------------------------------------------------------

  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_NAME" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_SUBCATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_SUBCATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_COST" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_BEGIN_DATE" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_TOTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" ADD CONSTRAINT "PROMO_PK" PRIMARY KEY ("PROMO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE NOVALIDATE;

--------------------------------------------------------
--  DDL for Table PROMOTIONS
--------------------------------------------------------

  CREATE TABLE "SH"."PROMOTIONS" 
   (	"PROMO_ID" NUMBER(6,0), 
	"PROMO_NAME" VARCHAR2(30 BYTE), 
	"PROMO_SUBCATEGORY" VARCHAR2(30 BYTE), 
	"PROMO_SUBCATEGORY_ID" NUMBER, 
	"PROMO_CATEGORY" VARCHAR2(30 BYTE), 
	"PROMO_CATEGORY_ID" NUMBER, 
	"PROMO_COST" NUMBER(10,2), 
	"PROMO_BEGIN_DATE" DATE, 
	"PROMO_END_DATE" DATE, 
	"PROMO_TOTAL" VARCHAR2(15 BYTE), 
	"PROMO_TOTAL_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_ID" IS 'primary key column';
   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_NAME" IS 'promotion description';
   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_SUBCATEGORY" IS 'enables to investigate promotion hierarchies';
   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_CATEGORY" IS 'promotion category';
   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_COST" IS 'promotion cost, to do promotion effect calculations';
   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_BEGIN_DATE" IS 'promotion begin day';
   COMMENT ON COLUMN "SH"."PROMOTIONS"."PROMO_END_DATE" IS 'promotion end day';
   COMMENT ON TABLE "SH"."PROMOTIONS"  IS 'dimension table without a PK-FK relationship with the facts table, to show outer join functionality';
--------------------------------------------------------
--  DDL for Index PROMO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SH"."PROMO_PK" ON "SH"."PROMOTIONS" ("PROMO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROMOTIONS
--------------------------------------------------------

  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_NAME" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_SUBCATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_SUBCATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_COST" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_BEGIN_DATE" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" MODIFY ("PROMO_TOTAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."PROMOTIONS" ADD CONSTRAINT "PROMO_PK" PRIMARY KEY ("PROMO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE NOVALIDATE;

--------------------------------------------------------
--  DDL for Table TIMES
--------------------------------------------------------

  CREATE TABLE "SH"."TIMES" 
   (	"TIME_ID" DATE, 
	"DAY_NAME" VARCHAR2(9 BYTE), 
	"DAY_NUMBER_IN_WEEK" NUMBER(1,0), 
	"DAY_NUMBER_IN_MONTH" NUMBER(2,0), 
	"CALENDAR_WEEK_NUMBER" NUMBER(2,0), 
	"FISCAL_WEEK_NUMBER" NUMBER(2,0), 
	"WEEK_ENDING_DAY" DATE, 
	"WEEK_ENDING_DAY_ID" NUMBER, 
	"CALENDAR_MONTH_NUMBER" NUMBER(2,0), 
	"FISCAL_MONTH_NUMBER" NUMBER(2,0), 
	"CALENDAR_MONTH_DESC" VARCHAR2(8 BYTE), 
	"CALENDAR_MONTH_ID" NUMBER, 
	"FISCAL_MONTH_DESC" VARCHAR2(8 BYTE), 
	"FISCAL_MONTH_ID" NUMBER, 
	"DAYS_IN_CAL_MONTH" NUMBER, 
	"DAYS_IN_FIS_MONTH" NUMBER, 
	"END_OF_CAL_MONTH" DATE, 
	"END_OF_FIS_MONTH" DATE, 
	"CALENDAR_MONTH_NAME" VARCHAR2(9 BYTE), 
	"FISCAL_MONTH_NAME" VARCHAR2(9 BYTE), 
	"CALENDAR_QUARTER_DESC" CHAR(7 BYTE), 
	"CALENDAR_QUARTER_ID" NUMBER, 
	"FISCAL_QUARTER_DESC" CHAR(7 BYTE), 
	"FISCAL_QUARTER_ID" NUMBER, 
	"DAYS_IN_CAL_QUARTER" NUMBER, 
	"DAYS_IN_FIS_QUARTER" NUMBER, 
	"END_OF_CAL_QUARTER" DATE, 
	"END_OF_FIS_QUARTER" DATE, 
	"CALENDAR_QUARTER_NUMBER" NUMBER(1,0), 
	"FISCAL_QUARTER_NUMBER" NUMBER(1,0), 
	"CALENDAR_YEAR" NUMBER(4,0), 
	"CALENDAR_YEAR_ID" NUMBER, 
	"FISCAL_YEAR" NUMBER(4,0), 
	"FISCAL_YEAR_ID" NUMBER, 
	"DAYS_IN_CAL_YEAR" NUMBER, 
	"DAYS_IN_FIS_YEAR" NUMBER, 
	"END_OF_CAL_YEAR" DATE, 
	"END_OF_FIS_YEAR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SH"."TIMES"."TIME_ID" IS 'primary key; day date, finest granularity, CORRECT ORDER';
   COMMENT ON COLUMN "SH"."TIMES"."DAY_NAME" IS 'Monday to Sunday, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."DAY_NUMBER_IN_WEEK" IS '1 to 7, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."DAY_NUMBER_IN_MONTH" IS '1 to 31, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."CALENDAR_WEEK_NUMBER" IS '1 to 53, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."FISCAL_WEEK_NUMBER" IS '1 to 53, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."WEEK_ENDING_DAY" IS 'date of last day in week, CORRECT ORDER';
   COMMENT ON COLUMN "SH"."TIMES"."CALENDAR_MONTH_NUMBER" IS '1 to 12, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."FISCAL_MONTH_NUMBER" IS '1 to 12, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."CALENDAR_MONTH_DESC" IS 'e.g. 1998-01, CORRECT ORDER';
   COMMENT ON COLUMN "SH"."TIMES"."FISCAL_MONTH_DESC" IS 'e.g. 1998-01, CORRECT ORDER';
   COMMENT ON COLUMN "SH"."TIMES"."DAYS_IN_CAL_MONTH" IS 'e.g. 28,31, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."DAYS_IN_FIS_MONTH" IS 'e.g. 25,32, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."END_OF_CAL_MONTH" IS 'last day of calendar month';
   COMMENT ON COLUMN "SH"."TIMES"."END_OF_FIS_MONTH" IS 'last day of fiscal month';
   COMMENT ON COLUMN "SH"."TIMES"."CALENDAR_MONTH_NAME" IS 'January to December, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."FISCAL_MONTH_NAME" IS 'January to December, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."CALENDAR_QUARTER_DESC" IS 'e.g. 1998-Q1, CORRECT ORDER';
   COMMENT ON COLUMN "SH"."TIMES"."FISCAL_QUARTER_DESC" IS 'e.g. 1999-Q3, CORRECT ORDER';
   COMMENT ON COLUMN "SH"."TIMES"."DAYS_IN_CAL_QUARTER" IS 'e.g. 88,90, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."DAYS_IN_FIS_QUARTER" IS 'e.g. 88,90, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."END_OF_CAL_QUARTER" IS 'last day of calendar quarter';
   COMMENT ON COLUMN "SH"."TIMES"."END_OF_FIS_QUARTER" IS 'last day of fiscal quarter';
   COMMENT ON COLUMN "SH"."TIMES"."CALENDAR_QUARTER_NUMBER" IS '1 to 4, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."FISCAL_QUARTER_NUMBER" IS '1 to 4, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."CALENDAR_YEAR" IS 'e.g. 1999, CORRECT ORDER';
   COMMENT ON COLUMN "SH"."TIMES"."FISCAL_YEAR" IS 'e.g. 1999, CORRECT ORDER';
   COMMENT ON COLUMN "SH"."TIMES"."DAYS_IN_CAL_YEAR" IS '365,366 repeating';
   COMMENT ON COLUMN "SH"."TIMES"."DAYS_IN_FIS_YEAR" IS 'e.g. 355,364, repeating';
   COMMENT ON COLUMN "SH"."TIMES"."END_OF_CAL_YEAR" IS 'last day of cal year';
   COMMENT ON COLUMN "SH"."TIMES"."END_OF_FIS_YEAR" IS 'last day of fiscal year';
   COMMENT ON TABLE "SH"."TIMES"  IS 'Time dimension table to support multiple hierarchies and materialized views';
--------------------------------------------------------
--  DDL for Index TIMES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SH"."TIMES_PK" ON "SH"."TIMES" ("TIME_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TIMES
--------------------------------------------------------

  ALTER TABLE "SH"."TIMES" MODIFY ("TIME_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("DAY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("DAY_NUMBER_IN_WEEK" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("DAY_NUMBER_IN_MONTH" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("CALENDAR_WEEK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("FISCAL_WEEK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("WEEK_ENDING_DAY" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("WEEK_ENDING_DAY_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("CALENDAR_MONTH_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("FISCAL_MONTH_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("CALENDAR_MONTH_DESC" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("CALENDAR_MONTH_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("FISCAL_MONTH_DESC" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("FISCAL_MONTH_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("DAYS_IN_CAL_MONTH" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("DAYS_IN_FIS_MONTH" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("END_OF_CAL_MONTH" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("END_OF_FIS_MONTH" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("CALENDAR_MONTH_NAME" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("FISCAL_MONTH_NAME" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("CALENDAR_QUARTER_DESC" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("CALENDAR_QUARTER_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("FISCAL_QUARTER_DESC" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("FISCAL_QUARTER_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("DAYS_IN_CAL_QUARTER" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("DAYS_IN_FIS_QUARTER" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("END_OF_CAL_QUARTER" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("END_OF_FIS_QUARTER" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("CALENDAR_QUARTER_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("FISCAL_QUARTER_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("CALENDAR_YEAR" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("CALENDAR_YEAR_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("FISCAL_YEAR" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("FISCAL_YEAR_ID" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("DAYS_IN_CAL_YEAR" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("DAYS_IN_FIS_YEAR" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("END_OF_CAL_YEAR" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" MODIFY ("END_OF_FIS_YEAR" NOT NULL ENABLE);
  ALTER TABLE "SH"."TIMES" ADD CONSTRAINT "TIMES_PK" PRIMARY KEY ("TIME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE NOVALIDATE;
